# -*- coding: utf-8 -*-
"""Cópia de Cópia de scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-ovV4vLT3R1KcSNFPE1ryJoHmpIHuRb
"""

import requests
from bs4 import BeautifulSoup

# Fazendo a requisição para a página de notícias
url = 'https://www.gov.br/saude/pt-br/vacinacao/calendario'
response = requests.get(url)
html = response.text

# Criando o objeto Beautiful Soup
soup = BeautifulSoup(html, 'html.parser')

# Buscando todos os elementos que contêm os títulos das notícias
titulos = soup.find_all('div', id='gestante')

# Extraindo e imprimindo os títulos
for titulo in titulos:
    print(titulo.text.strip())

import requests
from bs4 import BeautifulSoup

# Fazendo a requisição para a página de notícias
url = 'https://www.gov.br/saude/pt-br/vacinacao/calendario'
response = requests.get(url)
html = response.text

# Criando o objeto Beautiful Soup
soup = BeautifulSoup(html, 'html.parser')

# Buscando todos os elementos que contêm os títulos das notícias
titulos = soup.find_all('div', id='crianca')

# Extraindo e imprimindo os títulos
for titulo in titulos:
    print(titulo.text.strip())

import requests
from bs4 import BeautifulSoup

# Fazendo a requisição para a página de notícias
url = 'https://www.gov.br/saude/pt-br/vacinacao/calendario'
response = requests.get(url)
html = response.text

# Criando o objeto Beautiful Soup
soup = BeautifulSoup(html, 'html.parser')

# Buscando todos os elementos que contêm os títulos das notícias
titulos = soup.find_all('div', id='adolescente')

# Extraindo e imprimindo os títulos
for titulo in titulos:
    print(titulo.text.strip())

import requests
from bs4 import BeautifulSoup

# Fazendo a requisição para a página de notícias
url = 'https://www.gov.br/saude/pt-br/vacinacao/calendario'
response = requests.get(url)
html = response.text

# Criando o objeto Beautiful Soup
soup = BeautifulSoup(html, 'html.parser')

# Buscando todos os elementos que contêm os títulos das notícias
titulos = soup.find_all('div', id='adulto')

# Extraindo e imprimindo os títulos
for titulo in titulos:
    print(titulo.text.strip())

import requests
from bs4 import BeautifulSoup

# Fazendo a requisição para a página de notícias
url = 'https://www.gov.br/saude/pt-br/vacinacao/calendario'
response = requests.get(url)
html = response.text

# Criando o objeto Beautiful Soup
soup = BeautifulSoup(html, 'html.parser')

# Buscando todos os elementos que contêm os títulos das notícias
titulos = soup.find_all('div', id='idoso')

# Extraindo e imprimindo os títulos
for titulo in titulos:
    print(titulo.text.strip())